spring.application.name=employee
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:file:C:/Users/Akshay Chauhan/Downloads/Code Shuttle SpringBoot Course
spring.datasource.username=akshayDB
spring.datasource.password=akshay123
spring.jpa.hibernate.ddl-auto=update
